seed: 0
device: auto

paths:
  rosbag:
    path: "/home/takumi/bags/dataset.bag"
  dataset:
    train_data_dir: dataset/my_dataset/train
    test_data_dir: dataset/my_dataset/test

dataset:
  image_size: [85, 64]
  metric_waypoint_spacing: 0.05
  waypoint_spacing: 1
  context_size: 5
  len_traj_pred: 5
  min_goal_distance: 1
  max_goal_distance: 20
  min_action_distance: 0
  max_action_distance: 10
  normalize: true
  learn_angle: true
  negative_mining: true

collection:
  dataset_type: train
  trajectory_name: ""
  pose_source: odometry
  sample_dt: 0.25
  image_format: jpg

training:
  pretrained_checkpoint: weights/vint.pth
  freeze_encoder: true
  use_test: false
  tensorboard: true
  epochs: 20
  batch_size: 64
  num_workers: 4
  learning_rate: 0.00005
  weight_decay: 0.0001
  alpha: 0.5
  gradient_clip: 1.0
  scheduler: cosine
  resume: ""
